### PR TITLE
feat(dagster): upgrade to 1.4.10

### PR DESCRIPTION
**Pull request by walkoss**
## Summary

Bump dagster to 1.4.10 (from 1.3.13) `https://github.com/dagster-io/dagster/releases`
There are breaking changes and deprecations for the helm chart

## Test Plan

Local link + deploy
Launch new data pipelines in dagster 1.4.10

## Checklist

- [ ]  No images hosted from dockerhub
- [ ]  Are dashboards present to understand the health of the application.  There **must** be at least 1 of these
    - [ ]  all databases should have dashboards
    - [ ]  ideally also have at least cpu/mem utilization dashboards for webserver tier of the app
    - [ ]  you can use `plural from-grafana` to convert a grafana dashboard found via google to our CRD
- [ ]  Are scaling runbooks present
    - [ ]  all databases **must** have scaling runbooks
    - [ ]  you can use the charts in `pluralsh/module-library` to accelerate this
- [ ]  do you need to add config overlays?
    - [ ]  inputing secrets
    - [ ]  configuring autoscaling
- [ ]  If there’s a web-facing component to the app, we need to support OIDC authentication and setting up private networks if no authentication option is viable
- [ ]  All major clouds must be supported
    - [ ]  Azure
    - [ ]  AWS
    - [ ]  GCP

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
What are the breaking changes here?

**Comment by walkoss** [comment]
> What are the breaking changes here?

@michaeljguarino on the dagster release page (v1.4.0)

- Support for Python 3.7 has been dropped.
- build_asset_reconciliation_sensor (Experimental) has been removed. It was deprecated in 1.3 in favor of AutoMaterializePolicy.
- asset_key(s) properties on AssetIn and AssetDefinition have been removed in favor of key(s). These APIs were deprecated in 1.0.
- root_input_manager and RootInputManagerDefinition have been removed in favor of input_manager and InputManagerDefinition. These APIs were deprecated in 1.0.
- [dagster-pandas] The event_metadata_fn parameter on create_dagster_pandas_dataframe_type has been removed in favor of metadata_fn.
- [dagster-dbt] The library has been substantially revamped to support the new @dbt_assets and DbtCliResource. See the migration guide for details.
- Group names for dbt assets are now taken from a dbt model's group. Before, group names were determined using the model's subdirectory path.
- Support for dbt-rpc has been removed.
- The class alias DbtCloudResourceV2 has been removed.
- DbtCli has been renamed to DbtCliResource. Previously, DbtCliResource was a class alias for DbtCliClientResource.
- load_assets_from_dbt_project and load_assets_from_dbt_manifest now default to use_build=True.
- The default assignment of groups to dbt models loaded from load_assets_from_dbt_project and load_assets_from_dbt_manifest has changed. Rather than assigning a group name using the model’s subdirectory, a group name will be assigned using the dbt model’s [dbt group](https://docs.getdbt.com/docs/build/groups).
- The argument node_info_to_definition_metadata_fn for load_assets_from_dbt_project and load_assets_from_dbt_manifest now overrides metadata instead of adding to it.
- The arguments for load_assets_from_dbt_project and load_assets_from_dbt_manifest now must be specified using keyword arguments.
- When using the new DbtCliResource with load_assets_from_dbt_project and load_assets_from_dbt_manifest, stdout logs from the dbt process will now appear in the compute logs instead of the event logs.

**Comment by walkoss** [comment]
@michaeljguarino could we merge it? I've added a breaking flag anyway

**Review by michaeljguarino — APPROVED** [review]
I'm still not positive this needs to be marked breaking but we can leave it for now

**Comment by walkoss** [comment]
> I'm still not positive this needs to be marked breaking but we can leave it for now

Why aren't you positive?

**Pull request merged**
