### PR TITLE
adjusted variables accordingly to fix "culling"

### PR DESCRIPTION
**Pull request by tikr7**
Hi @DavidSpek 

We analyzed the issue of the "culling" feature of the notebook controller. In the end the names of the variables have changed (https://github.com/kubeflow/kubeflow/blob/master/components/proposals/20220121-jupyter-notebook-idleness.md#api-changes). 

This PR is to fix it.

I already tried it on our cluster by changing the configmap manually and we can confirm that it works.

### CODE REVIEW

**Review by michaeljguarino — APPROVED** [review]

**Review by michaeljguarino — COMMENTED** [review]
One thing: you'll need to bump the version on the containing chart to have this publish

**Comment by tikr7** [comment]
Is it now the correct version I need to bump?

@DavidSpek I also adjusted the notebook-controller version to 1.5.0 as agreed in the daily.
Interestingly, it was version 1.3 before as the image.

**Comment by DavidSpek** [comment]
You forgot to bump the version of the webapp image it seems.

**Comment by DavidSpek** [comment]
the image tag for the web app is v1.5.0

**Comment by tikr7** [comment]
Thanks! Updated.

**Comment by DavidSpek** [comment]
Thanks for the contribution!

**Pull request merged**
