### PR TITLE
feat(directus): oidc + default admin account + gcs backend

### PR DESCRIPTION
**Pull request by Walkoss**
## Summary
- Added OIDC (OIDC users should be manually added to a role using the admin user)
- Added default admin user
- Added GCS storage backend (need to add AWS and Azure later)
- Fixed postgres connection

## Test Plan
Local linking

## Additional info
Users who log in via OIDC are not automatically admin. They have to be added to a specific role by the admin. We can set the default role of the OIDC users but not knowing the uuid of the admin role (and not being able to set it manually), it is complicated to make the OIDC users be admin by default.
We can get the Admin role uuid from the api but how to inject the `AUTH_<PROVIDER>_DEFAULT_ROLE_ID` environment variable? Any suggestion @michaeljguarino 

## Checklist

- [x]  No images hosted from dockerhub
- [x]  Are dashboards present to understand the health of the application.  There **must** be at least 1 of these
    - [x]  all databases should have dashboards
    - [ ]  ideally also have at least cpu/mem utilization dashboards for webserver tier of the app
    - [ ]  you can use `plural from-grafana` to convert a grafana dashboard found via google to our CRD
- [x]  Are scaling runbooks present
    - [x]  all databases **must** have scaling runbooks
    - [x]  you can use the charts in `pluralsh/module-library` to accelerate this
- [ ]  do you need to add config overlays?
    - [ ]  inputing secrets
    - [ ]  configuring autoscaling
- [x]  If there’s a web-facing component to the app, we need to support OIDC authentication and setting up private networks if no authentication option is viable
- [ ]  All major clouds must be supported
    - [ ]  Azure
    - [ ]  AWS
    - [x]  GCP

### CODE REVIEW

**Comment by michaeljguarino** [comment]
Can you point me to the docs for directus admin role assignment?  It might be pretty tricky to do this

**Comment by michaeljguarino** [comment]
It's probably ok to just print out the admin user login credentials in `notes.tpl` and explain how to add users as admins after login if that's doable

**Comment by Walkoss** [comment]
> Can you point me to the docs for directus admin role assignment?  It might be pretty tricky to do this

Step 7 on https://docs.directus.io/self-hosted/sso.html#google to get an example

**Comment by michaeljguarino** [comment]
Yea so the best solution here is to fix an admin email and admin password, and then just document how to do the default role if necessary, but realistically you probably wouldn't want all plural logins to get admin anyway and the initial admin should assign a few manually.  It looks like a few env vars are all that's needed to set admin email and password and you could have them be recipe inputs also: https://docs.directus.io/self-hosted/quickstart.html

**Comment by Walkoss** [comment]
> Yea so the best solution here is to fix an admin email and admin password, and then just document how to do the default role if necessary, but realistically you probably wouldn't want all plural logins to get admin anyway and the initial admin should assign a few manually. It looks like a few env vars are all that's needed to set admin email and password and you could have them be recipe inputs also: https://docs.directus.io/self-hosted/quickstart.html

Yes already did that. I asked for the initial admin email in the recipe configuration and then output the generated password in notes.tpl

**Review by michaeljguarino — APPROVED** [review]

**Pull request merged**
