### PR TITLE
Update Datahub chart to use 0.2.151

### PR DESCRIPTION
**Pull request by justadevopsguy**
## Summary

Bump Datahub chart to use the latest one

## Checklist

- [ ]  No images hosted from dockerhub
- [ ]  Are dashboards present to understand the health of the application.  There **must** be at least 1 of these
    - [ ]  all databases should have dashboards
    - [ ]  ideally also have at least cpu/mem utilization dashboards for webserver tier of the app
    - [ ]  you can use `plural from-grafana` to convert a grafana dashboard found via google to our CRD
- [ ]  Are scaling runbooks present
    - [ ]  all databases **must** have scaling runbooks
    - [ ]  you can use the charts in `pluralsh/module-library` to accelerate this
- [ ]  do you need to add config overlays?
    - [ ]  inputing secrets
    - [ ]  configuring autoscaling
- [ ]  If there’s a web-facing component to the app, we need to support OIDC authentication and setting up private networks if no authentication option is viable
- [ ]  All major clouds must be supported
    - [ ]  Azure
    - [ ]  AWS
    - [ ]  GCP

### CODE REVIEW

**Comment by michaeljguarino** [comment]
Did you test it?  You should be able to test it by running:

```
plural link helm datahub --name datahub --path ../plural-artifacts/datahub/helm/datahub
plural build --only datahub --force
plural deploy
```

I can potentially try to test it too

**Comment by justadevopsguy** [comment]
> Did you test it? You should be able to test it by running:
> 
> ```
> plural link helm datahub --name datahub --path ../plural-artifacts/datahub/helm/datahub
> plural build --only datahub --force
> plural deploy
> ```
> 
> I can potentially try to test it too

Got this error 
image
Though I can see the chart version when I tried to search it 
image

**Comment by michaeljguarino** [comment]
@justadevopsguy you might need to drop the chart version bump for our wrapper chart to test (since your install repo likely still thinks its on the previous one)

**Comment by justadevopsguy** [comment]
> @justadevopsguy you might need to drop the chart version bump for our wrapper chart to test (since your install repo likely still thinks its on the previous one)

tried dropping the chart version but still same error. could you please try on you side as well?

**Comment by michaeljguarino** [comment]
So I just tested it but realized there are a lot of incompatibilities w/ datahub's new chart and it might be better to let us handle this upgrade since it'll be more advanced.  We can probably get it done in a few days.

**Comment by DavidSpek** [comment]
@justadevopsguy The PR we created to update datahub is https://github.com/pluralsh/plural-artifacts/pull/574/.

**Pull request closed without merging**
