### PR TITLE
fix(airbyte): upgrade to v0.44.8

### PR DESCRIPTION
**Pull request by gittysachin**
## Summary

Upgrade airbyte version

## Checklist

- [ ]  No images hosted from dockerhub
- [ ]  Are dashboards present to understand the health of the application.  There **must** be at least 1 of these
    - [ ]  all databases should have dashboards
    - [ ]  ideally also have at least cpu/mem utilization dashboards for webserver tier of the app
    - [ ]  you can use `plural from-grafana` to convert a grafana dashboard found via google to our CRD
- [ ]  Are scaling runbooks present
    - [ ]  all databases **must** have scaling runbooks
    - [ ]  you can use the charts in `pluralsh/module-library` to accelerate this
- [ ]  do you need to add config overlays?
    - [ ]  inputing secrets
    - [ ]  configuring autoscaling
- [ ]  If there’s a web-facing component to the app, we need to support OIDC authentication and setting up private networks if no authentication option is viable
- [ ]  All major clouds must be supported
    - [ ]  Azure
    - [ ]  AWS
    - [ ]  GCP

### CODE REVIEW

**Review by michaeljguarino — COMMENTED** [review]
was this tested?

**Comment by gittysachin** [comment]
Yes, @michaeljguarino tested [this](https://docs.plural.sh/adding-new-application/guide#_5-testing-locally) step by following all other dependent steps.

**Review by michaeljguarino — APPROVED** [review]
awesome, tested on our cluster as well and seems correct

**Review by michaeljguarino — APPROVED** [review]
awesome, tested on our cluster as well and seems correct

**Review by michaeljguarino — APPROVED** [review]
awesome, tested on our cluster as well and seems correct

**Pull request merged**
